$defs:
  FunctionDefinition:
    properties:
      commands:
        items:
          additionalProperties:
            type: object
          maxProperties: 1
          type: object
        title: Commands
        type: array
      description:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Description
      parameters:
        additionalProperties:
          $ref: '#/$defs/ParameterDefinition'
        default: {}
        title: Parameters
        type: object
      returns:
        anyOf:
        - items:
            $ref: '#/$defs/ReturnDefinition'
          type: array
        - type: 'null'
        default: []
        title: Returns
    required:
    - commands
    title: FunctionDefinition
    type: object
  ImportDefinition:
    properties:
      version:
        title: Version
        type: string
    required:
    - version
    title: ImportDefinition
    type: object
  ParameterDefinition:
    properties:
      description:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Description
      type:
        title: Type
        type: string
    required:
    - type
    title: ParameterDefinition
    type: object
  ReturnDefinition:
    properties:
      description:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Description
      type:
        title: Type
        type: string
    required:
    - type
    title: ReturnDefinition
    type: object
properties:
  author:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: Author
  description:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: Description
  functions:
    additionalProperties:
      $ref: '#/$defs/FunctionDefinition'
    default: {}
    title: Functions
    type: object
  imports:
    additionalProperties:
      $ref: '#/$defs/ImportDefinition'
    default: {}
    title: Imports
    type: object
  package:
    title: Package
    type: string
  version:
    title: Version
    type: string
required:
- package
- version
title: SourceFile
type: object
