name: Releasing package

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install poetry
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry install --with dev --with test
    - name: Build package
      run: |
        source .venv/bin/activate
        poetry build
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v3
      with:
        args: "dist/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
