name: Releasing package

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --all-extras
    - name: Build package
      run: |
        poetry build
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v3
      with:
        args: "dist/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
